# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vitaledge/v1/ddl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vitaledge/v1/ddl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16vitaledge/v1/ddl.proto\x12\x0cvitaledge.v1\"k\n CreateVertexPropertyIndexRequest\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\x10\n\x08property\x18\x03 \x01(\t\x12\x15\n\rif_not_exists\x18\x04 \x01(\x08\"N\n!CreateVertexPropertyIndexResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x08\x12\x18\n\x10indexed_entities\x18\x02 \x01(\x03\"i\n\x1e\x43reateEdgePropertyIndexRequest\x12\x0e\n\x06tenant\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\x10\n\x08property\x18\x03 \x01(\t\x12\x15\n\rif_not_exists\x18\x04 \x01(\x08\"L\n\x1f\x43reateEdgePropertyIndexResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x08\x12\x18\n\x10indexed_entities\x18\x02 \x01(\x03\x32\x82\x02\n\nDdlService\x12|\n\x19\x43reateVertexPropertyIndex\x12..vitaledge.v1.CreateVertexPropertyIndexRequest\x1a/.vitaledge.v1.CreateVertexPropertyIndexResponse\x12v\n\x17\x43reateEdgePropertyIndex\x12,.vitaledge.v1.CreateEdgePropertyIndexRequest\x1a-.vitaledge.v1.CreateEdgePropertyIndexResponseB;Z9github.com/spaceqraft/vitaledge/api/proto/vitaledge/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vitaledge.v1.ddl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/spaceqraft/vitaledge/api/proto/vitaledge/v1;v1'
  _globals['_CREATEVERTEXPROPERTYINDEXREQUEST']._serialized_start=40
  _globals['_CREATEVERTEXPROPERTYINDEXREQUEST']._serialized_end=147
  _globals['_CREATEVERTEXPROPERTYINDEXRESPONSE']._serialized_start=149
  _globals['_CREATEVERTEXPROPERTYINDEXRESPONSE']._serialized_end=227
  _globals['_CREATEEDGEPROPERTYINDEXREQUEST']._serialized_start=229
  _globals['_CREATEEDGEPROPERTYINDEXREQUEST']._serialized_end=334
  _globals['_CREATEEDGEPROPERTYINDEXRESPONSE']._serialized_start=336
  _globals['_CREATEEDGEPROPERTYINDEXRESPONSE']._serialized_end=412
  _globals['_DDLSERVICE']._serialized_start=415
  _globals['_DDLSERVICE']._serialized_end=673
# @@protoc_insertion_point(module_scope)
