# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vitaledge._proto.v1 import query_pb2 as vitaledge_dot_v1_dot_query__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vitaledge/v1/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/vitaledge.v1.QueryService/Execute',
                request_serializer=vitaledge_dot_v1_dot_query__pb2.QueryRequest.SerializeToString,
                response_deserializer=vitaledge_dot_v1_dot_query__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Explain = channel.unary_unary(
                '/vitaledge.v1.QueryService/Explain',
                request_serializer=vitaledge_dot_v1_dot_query__pb2.QueryRequest.SerializeToString,
                response_deserializer=vitaledge_dot_v1_dot_query__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/vitaledge.v1.QueryService/GetCapabilities',
                request_serializer=vitaledge_dot_v1_dot_query__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=vitaledge_dot_v1_dot_query__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.CreatePropertyIndex = channel.unary_unary(
                '/vitaledge.v1.QueryService/CreatePropertyIndex',
                request_serializer=vitaledge_dot_v1_dot_query__pb2.CreatePropertyIndexRequest.SerializeToString,
                response_deserializer=vitaledge_dot_v1_dot_query__pb2.CreatePropertyIndexResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePropertyIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=vitaledge_dot_v1_dot_query__pb2.QueryRequest.FromString,
                    response_serializer=vitaledge_dot_v1_dot_query__pb2.QueryResponse.SerializeToString,
            ),
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=vitaledge_dot_v1_dot_query__pb2.QueryRequest.FromString,
                    response_serializer=vitaledge_dot_v1_dot_query__pb2.ExplainResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=vitaledge_dot_v1_dot_query__pb2.CapabilitiesRequest.FromString,
                    response_serializer=vitaledge_dot_v1_dot_query__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'CreatePropertyIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePropertyIndex,
                    request_deserializer=vitaledge_dot_v1_dot_query__pb2.CreatePropertyIndexRequest.FromString,
                    response_serializer=vitaledge_dot_v1_dot_query__pb2.CreatePropertyIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vitaledge.v1.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vitaledge.v1.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vitaledge.v1.QueryService/Execute',
            vitaledge_dot_v1_dot_query__pb2.QueryRequest.SerializeToString,
            vitaledge_dot_v1_dot_query__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vitaledge.v1.QueryService/Explain',
            vitaledge_dot_v1_dot_query__pb2.QueryRequest.SerializeToString,
            vitaledge_dot_v1_dot_query__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vitaledge.v1.QueryService/GetCapabilities',
            vitaledge_dot_v1_dot_query__pb2.CapabilitiesRequest.SerializeToString,
            vitaledge_dot_v1_dot_query__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePropertyIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vitaledge.v1.QueryService/CreatePropertyIndex',
            vitaledge_dot_v1_dot_query__pb2.CreatePropertyIndexRequest.SerializeToString,
            vitaledge_dot_v1_dot_query__pb2.CreatePropertyIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
